"use strict";
/* Self-contained review page for a story-led lesson (lesson.json from story.js): the full story,
   teaching, activities and quiz, every claim with its source URL and verbatim passage, the support
   check for every pupil-facing sentence, and every warning. Images inline as base64. Provisional.
   Usage: node review-page.js LESSON_DIR OUT.html [--player player.html] */
var fs = require("fs");
var path = require("path");
function arg(name, fallback) { var at = process.argv.indexOf("--" + name); return at !== -1 ? process.argv[at + 1] : fallback; }
function e(s) { return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c]; }); }

function build(lessonDir, out, opts) {
  opts = opts || {};
  var L = JSON.parse(fs.readFileSync(path.join(lessonDir, "lesson.json"), "utf8"));
  var story = L.story;
  var claims = {}; L.claims.forEach(function (c) { claims[c.id] = c; });
  var support = {}; (L.checks.support.rows || []).forEach(function (r) { support[r.id] = r; });
  var images = {}; (L.images || []).forEach(function (i) { images[i.id] = i; });
  function img(id) {
    var a = images[id]; if (!a || a.status !== "ready") return a ? "<p class=\"muted\">Picture " + e(id) + " not generated.</p>" : "";
    var file = path.join(lessonDir, "images", id + ".jpg");
    if (!fs.existsSync(file)) return "";
    return "<figure><img alt=\"" + e(a.frameLabel) + "\" src=\"data:image/jpeg;base64," + fs.readFileSync(file).toString("base64") + "\"><figcaption>" + e(a.frameLabel) + "</figcaption></figure>";
  }
  function chips(ids) { return (ids || []).map(function (id) { return "<a class=\"chip\" href=\"#" + e(id) + "\">" + e(id) + "</a>"; }).join(" "); }
  function check(id) { var r = support[id]; if (!r) return ""; return "<span class=\"v v-" + e(r.ok ? (r.factual ? "ok" : "story") : "bad") + "\" title=\"" + e(r.problem) + "\">" + e(r.ok ? (r.factual ? "fact: supported" : "story") : r.verdict) + "</span>"; }
  var h = [];
  h.push("<!DOCTYPE html><html lang=\"en-GB\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; style-src 'unsafe-inline'; img-src data:\"><title>Wondii review: " + e(story.title) + " (provisional)</title><style>" +
    "body{font:15px/1.5 system-ui,sans-serif;margin:0;color:#1d2330;background:#f6f5f1}main{max-width:1000px;margin:0 auto;padding:20px}h1{font-size:26px;margin:.2em 0}h2{margin-top:2em;border-bottom:2px solid #d9d4c7;padding-bottom:4px}h3{margin:1.2em 0 .3em}" +
    ".note{background:#fff3cd;border:1px solid #b38600;padding:10px 14px;border-radius:10px}.muted{color:#667}figure{margin:10px 0}figure img{max-width:100%;border-radius:10px;display:block}figcaption{font-size:13px;color:#556}" +
    ".beat{margin:4px 0;padding:6px 10px;background:#fff;border-radius:8px;border-left:4px solid #c9c2b0}.beat.r-problem{border-color:#c0392b}.beat.r-discovery{border-color:#8e44ad}.beat.r-explain,.beat.r-example,.beat.r-compare{border-color:#2471a3}.beat.r-use{border-color:#1e8449}" +
    ".role{font:700 11px system-ui;text-transform:uppercase;color:#667;margin-right:6px}.chip{font:600 11px monospace;background:#e8eef7;color:#1a3d6d;padding:1px 6px;border-radius:6px;text-decoration:none}.v{font:600 11px system-ui;padding:1px 6px;border-radius:6px;margin-left:6px}.v-ok{background:#d5f5e3;color:#145a32}.v-story{background:#eee;color:#555}.v-bad{background:#fadbd8;color:#78281f}" +
    ".claim{background:#fff;border-radius:10px;padding:10px 14px;margin:10px 0}.claim blockquote{margin:6px 0;padding:6px 10px;background:#f4f1e8;border-left:3px solid #b38600;font-size:13.5px}mark{background:#ffe58a}table{border-collapse:collapse;width:100%;font-size:13px;background:#fff}td,th{border:1px solid #ddd;padding:4px 6px;vertical-align:top;text-align:left}.ok{color:#145a32}.bad{color:#78281f}.act{background:#fff;border:2px solid #1e8449;border-radius:10px;padding:10px 14px;margin:8px 0}" +
    "</style></head><body><main>");
  h.push("<p class=\"note\"><b>Provisional. Not classroom-ready. Not human-reviewed.</b> Generated by Wondii's story-led research mode (" + e(L.label || "") + ") on " + e(L.generatedAt) + ". All lesson text is the generator's output, unchanged." + (opts.player ? " <a href=\"" + e(opts.player) + "\">Open the playable lesson</a>." : "") + "</p>");
  h.push("<h1>" + e(story.title) + "</h1><p class=\"muted\">Teacher prompt: “" + e(L.request.lessonText) + "” · " + e(L.request.yearGroup) + " · " + e(L.request.subject) + " · " + e(L.request.requestedMinutes) + " minutes requested · estimated " + e(L.adventure.estimateMinutes) + " minutes</p>");
  h.push("<p><b>Checking policy.</b> " + e(L.policy) + "</p>");
  h.push("<p><b>Interaction.</b> " + e(L.interaction) + "</p>");
  h.push("<h2>Contents</h2><ol><li><a href=\"#story\">Story and teaching, scene by scene</a></li><li><a href=\"#quiz\">End quiz</a></li><li><a href=\"#warnings\">Warnings (" + L.warnings.length + ")</a></li><li><a href=\"#claims\">Claims with sources (" + L.claims.length + ")</a></li><li><a href=\"#support\">Support check for every sentence</a></li><li><a href=\"#style\">Character and style sheet</a></li><li><a href=\"#images\">Picture checks</a></li><li><a href=\"#sources\">Sources and research</a></li></ol>");
  h.push("<h2>The story</h2><p><b>Setting:</b> " + e(story.setting) + "<br><b>Goal:</b> " + e(story.goal) + "<br><b>Stakes:</b> " + e(story.stakes) + "</p><p><b>Characters:</b></p><ul>" + story.characters.map(function (c) { return "<li><b>" + e(c.name) + "</b>, " + e(c.role) + (c.personality ? " (" + e(c.personality) + ")" : "") + ". Look: " + e(c.look) + "</li>"; }).join("") + "</ul>");
  h.push("<h3>The ideas taught</h3><ol>" + L.ideas.map(function (i) { return "<li><b>" + e(i.title) + "</b>: " + e(i.question) + " <span class=\"muted\">(" + e(i.curriculumLink) + (i.linksTo ? "; builds on " + e(i.linksTo) : "") + ")</span></li>"; }).join("") + "</ol>");
  h.push("<h2 id=\"story\">Story and teaching, scene by scene</h2>");
  story.scenes.forEach(function (s) {
    h.push("<h3>" + e(s.title) + " <span class=\"muted\">(" + e(s.kind) + (s.ideaId ? ", idea " + e(s.ideaId) : "") + ")</span></h3>");
    h.push(img("scene-" + s.id));
    s.beats.forEach(function (b, i) { h.push("<div class=\"beat r-" + e(b.role) + "\"><span class=\"role\">" + e(b.role) + "</span>" + (b.speaker && !/^narrator$/i.test(b.speaker) ? "<b>" + e(b.speaker) + ":</b> " : "") + e(b.text) + " " + chips(b.claimIds) + check(s.id + ".b" + i) + "</div>"); });
    if (s.teachingImage) h.push("<p class=\"muted\">Teaching picture asked for: " + e(s.teachingImage.view) + " of " + e(s.teachingImage.subject) + (s.teachingImage.comparedWith ? " with " + e(s.teachingImage.comparedWith) : "") + "; feature: " + e(s.teachingImage.feature) + " " + chips(s.teachingImage.claimIds) + "</p>" + img("teach-" + s.id));
    var a = s.activity;
    if (a) h.push("<div class=\"act\"><b>Class activity (choose):</b> " + e(a.instruction) + check(s.id + ".act.instruction") + "<br><i>" + e(a.newCase) + "</i>" + check(s.id + ".act.newCase") + "<ul>" + a.choices.map(function (c, i) { return "<li class=\"" + (c.correct ? "ok" : "bad") + "\"><b>" + e(c.text) + "</b> " + (c.correct ? "(correct)" : "(wrong)") + ": " + e(c.feedback) + " " + chips(c.claimIds) + check(s.id + ".act.c" + i + ".feedback") + "</li>"; }).join("") + "</ul>Success: " + e(a.successText) + check(s.id + ".act.successText") + "</div>");
  });
  h.push("<h3>Resolution</h3>" + img("scene-resolution") + story.resolution.map(function (b, i) { return "<div class=\"beat\">" + (b.speaker && !/^narrator$/i.test(b.speaker) ? "<b>" + e(b.speaker) + ":</b> " : "") + e(b.text) + " " + chips(b.claimIds) + check("resolution.b" + i) + "</div>"; }).join(""));
  h.push("<h3>Recap</h3><ul>" + story.recap.map(function (r, i) { return "<li>" + e(r.text) + " " + chips(r.claimIds) + check("recap.r" + i) + "</li>"; }).join("") + "</ul>");
  h.push("<h2 id=\"quiz\">End quiz (" + story.quiz.length + " questions)</h2><ol>" + story.quiz.map(function (q, i) { return "<li><b>" + e(q.prompt) + "</b><ul>" + q.choices.map(function (c) { return "<li class=\"" + (c === q.correct ? "ok" : "") + "\">" + e(c) + (c === q.correct ? " ✔" : "") + "</li>"; }).join("") + "</ul>Explanation: " + e(q.explain) + " " + chips(q.claimIds) + check("quiz.q" + i + ".answer") + check("quiz.q" + i + ".explain") + "</li>"; }).join("") + "</ol>");
  h.push("<h2 id=\"warnings\">Warnings (" + L.warnings.length + ", non-blocking)</h2>" + (L.warnings.length ? "<table><tr><th>Check</th><th>Warning</th></tr>" + L.warnings.map(function (w) { return "<tr><td>" + e(w.check) + "</td><td>" + e(w.text) + "</td></tr>"; }).join("") + "</table>" : "<p>None.</p>"));
  var first = {}; (L.checks.support.firstPass || []).forEach(function (r) { first[r.id] = r; });
  var repairRows = [];
  (L.repairs || []).forEach(function (r) {
    if (r.kind === "support") (r.applied || []).forEach(function (id) { var a = first[id], b = support[id]; repairRows.push("<tr><td>" + e(id) + "</td><td>one automatic repair (first check: " + e(a ? a.verdict + ": " + a.problem : "") + ")<br>before: " + e(a ? a.text : "") + "<br>after: " + e(b ? b.text : "") + "</td></tr>"); });
    if (r.kind === "questions") repairRows.push("<tr><td>quiz</td><td>question rewrite asked for " + e((r.asked || []).join(", ")) + "; kept " + e(JSON.stringify(r.replaced || [])) + "</td></tr>");
  });
  (L.fallbacks || []).forEach(function (f) { repairRows.push("<tr><td>" + e(f.id) + "</td><td>fallback: " + e(f.action) + (f.was ? "<br>was: " + e(f.was) : "") + (f.now ? "<br>now: " + e(f.now) : "") + (f.problem ? "<br>reason: " + e(f.problem) : "") + "</td></tr>"); });
  if (repairRows.length) h.push("<h3>Automatic repairs and fallbacks</h3><table><tr><th>Item</th><th>What happened</th></tr>" + repairRows.join("") + "</table>");
  h.push("<h2 id=\"claims\">Claims with sources (" + L.claims.length + ")</h2><p class=\"muted\">Each claim's quote was found word for word in its passage by code, then an automated entailment check confirmed the claim says no more than the quote.</p>");
  L.claims.forEach(function (c) {
    var passage = e(c.passage || "");
    var q = e(c.quote || "");
    if (q && passage.indexOf(q) !== -1) passage = passage.replace(q, "<mark>" + q + "</mark>");
    h.push("<div class=\"claim\" id=\"" + e(c.id) + "\"><b>" + e(c.id) + "</b> <span class=\"muted\">(" + e(c.role) + ", idea " + e(c.ideaId) + ")</span><br>" + e(c.text) + "<br>Quote: “" + q + "”<br>Source: <a href=\"" + e(c.url) + "\">" + e(c.title || c.url) + "</a> <span class=\"muted\">" + e(c.url) + " · passage " + e((c.sourceRef || []).join(", ")) + " · entailment: " + e(c.entailment && c.entailment.verdict || c.entailment || "") + "</span><blockquote>" + passage + "</blockquote></div>");
  });
  if ((L.heldClaims || []).length) h.push("<h3>Claims held back (not used)</h3><ul>" + L.heldClaims.map(function (c) { return "<li>" + e(c.text) + " <span class=\"muted\">" + e(c.reason || (c.entailment && c.entailment.verdict) || "") + "</span></li>"; }).join("") + "</ul>");
  h.push("<h2 id=\"support\">Support check (hard block) for every pupil-facing sentence</h2><p>" + L.checks.support.items + " items; " + L.checks.support.firstPassFailing + " failed the first pass; " + L.checks.support.failing + " fail now.</p><table><tr><th>Item</th><th>Text</th><th>Claims</th><th>Result</th></tr>" + L.checks.support.rows.map(function (r) { return "<tr><td>" + e(r.id) + "</td><td>" + e(r.text) + "</td><td>" + chips(r.claimIds) + "</td><td class=\"" + (r.ok ? "ok" : "bad") + "\">" + e(r.ok ? (r.factual ? "fact: supported" : "story only") : r.verdict + ": " + r.problem) + "</td></tr>"; }).join("") + "</table>");
  // How the pictures were made: one cast/style sheet, every picture drawn from it; sizes and framing.
  var made = (L.images || []).filter(function (i) { return i.id !== "cast-sheet" && i.status === "ready"; });
  h.push("<h2 id=\"style\">Character and style reference sheet</h2><p>Drawn first, in one locked art style. Every picture with characters was drawn with this sheet as the reference image (image edits endpoint), so faces, hair and outfits stay the same; pictures without characters use it for style only. It is not shown to pupils.</p>" + img("cast-sheet") +
    "<table><tr><th>Picture</th><th>Drawn from the sheet</th><th>Size rule</th></tr>" + made.map(function (i) {
      var size = i.type !== "teaching" || !i.scaleCharacter ? "n/a" : i.sourcedSize ? "sourced size: " + i.sourcedSize : "no sourced size: modest size, neutral framing (no size comparison)";
      return "<tr><td>" + e(i.id) + "</td><td>" + (i.referenceUsed ? "yes" : "no") + "</td><td>" + e(size) + "</td></tr>";
    }).join("") + "</table>");
  h.push("<h2 id=\"images\">Picture checks (automated, non-blocking)</h2>" + ((L.checks.vision || []).length ? "<table><tr><th>Picture</th><th>What the checker saw</th><th>Flags</th></tr>" + L.checks.vision.map(function (v) { return "<tr><td>" + e(v.id) + "</td><td>" + e(v.whatIsShown) + "</td><td class=\"" + (v.ok ? "ok" : "bad") + "\">" + e(v.ok ? "none" : v.flags.join("; ")) + "</td></tr>"; }).join("") + "</table>" : "<p>No picture checks recorded.</p>"));
  h.push("<h2 id=\"sources\">Sources and research</h2><ul>" + (L.sources || []).map(function (s) { return "<li>" + e(s.sourceId) + ": <a href=\"" + e(s.url) + "\">" + e(s.title || s.url) + "</a> <span class=\"muted\">" + e(s.publisher || s.host || "") + " · " + e(s.tier || "") + "</span></li>"; }).join("") + "</ul>");
  if ((L.discoverySources || []).length) h.push("<p class=\"muted\">Discovery only (used to find authoritative pages, never cited): " + L.discoverySources.map(function (s) { return e(s.url); }).join(", ") + "</p>");
  h.push("<p class=\"muted\">Search providers: " + e(JSON.stringify(L.searchProviders || [])) + "</p>");
  h.push("<p class=\"muted\">Models: " + e(JSON.stringify(L.models || {})) + " · Spend for this lesson (guard = 2× listed): " + e(JSON.stringify(L.spend || {})) + "</p>");
  h.push("</main></body></html>");
  fs.writeFileSync(out, h.join("\n"));
  return { bytes: h.join("\n").length };
}
if (require.main === module) console.log(JSON.stringify(build(process.argv[2], process.argv[3], { player: arg("player", "") })));
module.exports = { build: build };
